# Numpy Basics

In [2]:
import numpy as np

## Arrays aus Listen erstellen

In [3]:
array_dim1 = np.array([1, 2, 3, 4])
array_dim1

array([1, 2, 3, 4])

In [4]:
array_dim2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_dim2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
array_dim3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array_dim3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

## Indexing/Slicing

In [6]:
array_dim1[0]

1

In [7]:
array_dim1[:2]

array([1, 2])

In [8]:
array_dim1[-1]

4

In [9]:
print(array_dim2)
array_dim2[:3, 0]

[[1 2 3 4]
 [5 6 7 8]]


array([1, 5])

In [10]:
print(array_dim2[:3, 0])
print(f"Shape: {array_dim2[:3, 0].shape}")

print(array_dim2[:3, 0:1])
print(f"Shape: {array_dim2[:3, 0:1].shape}")

[1 5]
Shape: (2,)
[[1]
 [5]]
Shape: (2, 1)


In [11]:
array_dim1[0:5:2] # slice: [start:stop:step]

array([1, 3])

**Boolean indexing**

In [12]:
array_dim1[array_dim1 > 2]

array([3, 4])

In [13]:
array_dim2[(array_dim2 > 2) & (array_dim2 < 6)]

array([3, 4, 5])

## Standard Arrays erstellen

In [14]:
array_sequence = np.arange(10)
array_sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array_zeros = np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
array_ones = np.ones((10,10))
array_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Nützliche Funktionen/Methoden

In [17]:
array_gauss = np.random.randn(10)
array_gauss

array([ 0.82376619, -0.87445539, -1.83532907, -0.4990242 ,  0.6008399 ,
        0.15068246, -0.38521297,  0.3138987 ,  1.17724671,  0.56180191])

In [18]:
array_gauss.sort()
array_gauss

array([-1.83532907, -0.87445539, -0.4990242 , -0.38521297,  0.15068246,
        0.3138987 ,  0.56180191,  0.6008399 ,  0.82376619,  1.17724671])

In [19]:
array_gauss.astype(int)

array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  1])

In [20]:
array_gauss.max()

1.1772467143868617

In [21]:
print(array_dim1)
array_dim1.cumsum()

[1 2 3 4]


array([ 1,  3,  6, 10])

## Elementweiße Operationen

In [22]:
print(array_sequence)
print(array_gauss)

[0 1 2 3 4 5 6 7 8 9]
[-1.83532907 -0.87445539 -0.4990242  -0.38521297  0.15068246  0.3138987
  0.56180191  0.6008399   0.82376619  1.17724671]


In [23]:
array_sequence + array_gauss

array([-1.83532907,  0.12554461,  1.5009758 ,  2.61478703,  4.15068246,
        5.3138987 ,  6.56180191,  7.6008399 ,  8.82376619, 10.17724671])

In [24]:
array_sequence - array_gauss

array([1.83532907, 1.87445539, 2.4990242 , 3.38521297, 3.84931754,
       4.6861013 , 5.43819809, 6.3991601 , 7.17623381, 7.82275329])

In [25]:
array_sequence * array_gauss

array([-0.        , -0.87445539, -0.9980484 , -1.15563892,  0.60272985,
        1.56949352,  3.37081144,  4.20587928,  6.59012953, 10.59522043])

In [26]:
array_sequence / array_gauss

array([-0.        , -1.14356892, -4.00782167, -7.7878997 , 26.54588947,
       15.92870544, 10.67992103, 11.65035817,  9.71149349,  7.64495657])

Operationen zwischen Arrays unterschiedlicher Dimensionen möglich

In [27]:
print(array_ones)
print(array_sequence)
array_sequence + array_ones

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

## Statistiken

### Aufgaben

### Berechnen Sie die den Mittelwert des arrays `a` "von Hand" und vergleichen das Ergebnis mit dem der numpy Funktion `mean()`

In [28]:
a = np.array([1, 5, 17, 3, 22])

In [29]:
mean_a = a.sum()/len(a)
mean_a

9.6

In [30]:
a.mean()

9.6

### Berechnen Sie die Varianz des arrays `a` "von Hand" (nutzen Sie dafür gerne `np.mean()` und `**2` oder `np.square()`) und vergleichen das Ergebnis mit dem der numpy Funktion `var()`

In [31]:
var = np.mean((a - np.mean(a))**2)
var

69.44000000000001

In [32]:
a.var()

69.44000000000001

### Berechnen Sie die Covarianz der arrays `a` und `b` "von Hand" und vergleichen das Ergebnis mit dem der numpy Funktion `cov()`, die die Covarianzmatrix ausgibt. Fällt Ihnen etwas auf?

In [34]:
b = np.array([2, 4, 5, 10, 15])

In [ ]:
cov = np.mean((a - np.mean(a)) * (b - np.mean(b)))
cov

24.28

In [52]:
cov_matrix = np.cov(a, b, bias=True)

### Zuletzt, berechnen Sie den Korrelationskoeffizienten nach Pearson für a und b. Sie können dafür alle Numpy Funktionen verwenden, bis auf `np.corrcoef()`. Vergleichen Sie ihr Ergebnis mit dem von `np.corrcoef()`

In [53]:
corr = cov_matrix[1, 0]/(np.std(a) * np.std(b))
corr

0.6189548185940389

In [54]:
np.corrcoef(a, b)

array([[1.        , 0.61895482],
       [0.61895482, 1.        ]])